'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import requests
import json

class client(object):

    def __init__(self, Sid, AuthToken, BaseUrl):

        self.Sid = Sid
        self.AuthToken = AuthToken
        self.BaseUrl = BaseUrl

class AccountDetails(object):

    def __init__(self,client):
        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl

    def Details(self):

        Url=self.BaseUrl+'/Accounts.json/'+self.Sid
        r1=requests.get(Url, auth=(self.Sid,self.AuthToken))
        content = json.loads(r1.text)

        return content

class ChangeAccountPassword(object):

    def __init__(self, Password, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.Password = Password

    def ChangePassword(self):

        Url = self.BaseUrl+'/Accounts.json/'+self.Sid
        data = {'AccountSid': self.Sid, 'Password': self.Password}
        r2 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
        content = json.loads(r2.text)
        return content

class CreateSubAccount(object):

    def __init__(self, FriendlyName, EmailAddress, Password, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.Password = Password
        self.FriendlyName = FriendlyName
        self.EmailAddress = EmailAddress

    def Create(self):

        Url = self.BaseUrl+'/Accounts.json/'
        data = {'FriendlyName': self.FriendlyName, 'EmailAddress': self.EmailAddress, 'Password': self.Password}
        r3 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))

        content = json.loads(r3.text)
        return content

class CloseSubAccount(object):

    def __init__(self, SubSid, client):
        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.SubSid = SubSid

    def Close(self):

        Url = self.BaseUrl+'/Accounts.json/'+self.SubSid
        data = {'Status': 'closed'}
        r3 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))

        content = json.loads(r3.text)
        return content

class SubAccountDetails(object):

    def __init__(self, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl

    def Details(self):

        Url = self.BaseUrl+'/Accounts.json/'
        r4 = requests.get(Url, auth=(self.Sid, self.AuthToken))
        content = json.loads(r4.text)
        return content