'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import requests
import json

class client(object):

    def __init__(self, Sid, AuthToken, BaseUrl):

        self.Sid = Sid
        self.AuthToken = AuthToken
        self.BaseUrl = BaseUrl

class Makecall(object):

    def __init__(self, From, To, Url, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.From = From
        self.To = To
        self.Url = Url

    def Call(self):

        try:

            Url = self.BaseUrl+'/Accounts/'+self.Sid+'/Calls.json'
            data = {'From': self.From, 'To': self.To, 'Url': self.Url}

            r1 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
            if r1.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r1.status_code == 404:
                return "Base Url is Incorrect! Please verify and try again"
            elif r1.status_code == 400:
                return "Invalid Number"
            else:
                content = json.loads(r1.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class GetCallDetail(object):

    def __init__(self, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl

    def GetDetails(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Calls.json'
            r2 = requests.get(Url, auth=(self.Sid, self.AuthToken))

            if r2.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r2.status_code == 404:
                return "Base Url is Incorrect! Please verify and try again"
            else:
                content = json.loads(r2.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class RedirectCall(object):

    def __init__(self, Url, SubSid, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.Url = Url
        self.SubSid = SubSid

    def Redirect(self):

        try:

            data = {'Url': self.Url}
            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Calls.json/'+self.SubSid
            r3 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))

            if r3.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r3.status_code == 404:
                return "Base Url or Sub Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r3.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class ConferenceCall(object):

    def __init__(self, sig_Url, SubSid, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.SubSid = SubSid
        self.sig_Url = sig_Url

    def Conference(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Calls.json/' + self.SubSid
            data = {'Url': self.sig_Url, 'MoveConnectedCallLeg': 'true'}

            r4 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
            if r4.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r4.status_code == 404:
                return "Base Url or Sub Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r4.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class MuteParticipant(object):

    def __init__(self, ParticipantSid, ConferenceSid, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.ParticipantSid = ParticipantSid
        self.ConferenceSid = ConferenceSid

    def Mute(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Conferences.json/' + self.ConferenceSid + '/Participants.json/' + self.ParticipantSid
            data = {'Mute': 'true'}

            r5 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
            if r5.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r5.status_code == 404:
                return "Base Url/Participant Sid/Conference Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r5.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class UnMuteParticipant(object):

    def __init__(self, ParticipantSid, ConferenceSid, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.ParticipantSid = ParticipantSid
        self.ConferenceSid = ConferenceSid

    def UnMute(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Conferences.json/' + self.ConferenceSid + '/Participants.json/' + self.ParticipantSid
            data = {'Mute': 'false'}

            r6 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
            if r6.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r6.status_code == 404:
                return "Base Url/Participant Sid/Conference Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r6.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")
