'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import unittest

import vcr

from Restcomm_Python_SDk.Restcomm.IncomingNumber import IncomingNumber


class TestPhoneNumberList(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_GetList(self):

        try:

                Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
                AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
                BaseUrl = 'https://mockServer.com/mock/2012-04-24'

                data = IncomingNumber.client(Sid, AuthToken, BaseUrl)
                content = IncomingNumber.PhoneNumberList(data).GetList()

                self.assertIsNotNone(content)

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")

class TestAttachPhoneNumber(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_Attach(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'
            phNumber = '5065'
            VoiceUrl = 'https://mockServer.com/mock/demos/hello-play.xml'

            data = IncomingNumber.client(Sid, AuthToken, BaseUrl)
            content = IncomingNumber.AttachPhoneNumber(phNumber, VoiceUrl, data).Attach()

            self.assertIsNotNone(content)

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")


class TestDeletePhoneNumber(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_Delete(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'
            CallSid = 'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP'

            data = IncomingNumber.client(Sid, AuthToken, BaseUrl)
            content = IncomingNumber.DeletePhoneNumber(CallSid, data).Delete()

            self.assertIsNotNone(content)
            self.assertEqual(content, "Deleted")

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")

if __name__ == '__main__':
    unittest.main()