'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import unittest
import nose
import vcr

from Restcomm_Python_SDk.Restcomm.Client import Client


class TestCreateClient(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_Create(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'
            Login = 'noOne'
            Password = 'dummyPassword321'

            data = Client.client(Sid, AuthToken, BaseUrl)
            content = Client.CreateClient(Login, Password, data).Create()

            self.assertIsNotNone(content)
            self.assertNotEqual(content["sid"], Sid)

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")

class TestChangePassword(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_Change(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'
            ClientSid = 'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP'
            Password = 'dummyPassword123'

            data = Client.client(Sid, AuthToken, BaseUrl)
            content = Client.ChangeClientPassword(ClientSid, Password, data).ChangePassword()

            self.assertIsNotNone(content)

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")


class TestClientList(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_list(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'

            data = Client.client(Sid, AuthToken, BaseUrl)
            content = Client.ClientList(data).GetList()

            self.assertIsNotNone(content)

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")
        except IndexError:
            print("Index Error: list Index out of range")

class DeleteClient(unittest.TestCase):

    @vcr.use_cassette(record_mode='new_episodes')
    def test_Delete(self):

        try:

            Sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            AuthToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
            BaseUrl = 'https://mockServer.com/mock/2012-04-24'
            ClientSid = 'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP'

            data = Client.client(Sid, AuthToken, BaseUrl)
            content = Client.DeleteClient(ClientSid, data).Delete()

            self.assertIsNotNone(content)
            self.assertEqual(content, 'Deleted')

        except FileNotFoundError:
            print("FileNotFound Error: File not found. please check and try again!")
        except ImportError:
            print("Import Error: Please Import proper library!")
        except TypeError:
            print("Type Error: the value is of wrong type")

if __name__ == '__main__':
    unittest.main()
    nose.main()