'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.

 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import requests
import json

class client(object):

    def __init__(self, Sid, AuthToken, BaseUrl):

        self.Sid = Sid
        self.AuthToken = AuthToken
        self.BaseUrl = BaseUrl

class IPDevice(object):

    def __init__(self, DIdentifier, IPAddress, client):

        self.Sid = client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.DIdentifier = DIdentifier
        self.IPAddress = IPAddress

    def GetLocation(self):

        Url = self.BaseUrl+'/Accounts/'+self.Sid+'/Geolocation/Immediate.json'
        address = self.IPAddress+'/'+self.Sid
        data = {'DeviceIdentifier': self.DIdentifier, 'StatusCallback': address}

        r1 = requests.post(Url, data=data, auth=(self.Sid, self.AuthToken))
        print(r1.status_code)

def main():

    Sid = 'AC43b4d94a9b2b1862583c8638b70d26f2'
    AuthToken = '0cfe8579a1faace43ae968b33f9d45f0'
    BaseUrl = 'https://cloud.restcomm.com/restcomm/2012-04-24'
    DIdentifier = 'client:nukles1.07'
    IPAddress = 'https://192.16.1.19:8080'

    data = client(Sid, AuthToken, BaseUrl)
    content = IPDevice(DIdentifier, IPAddress, data).GetLocation()

if __name__ == '__main__':
    main()