= *Restcomm-Python* +

Restcomm_Python_SDk is a module for using the *Restcomm Rest API*. This Documentation provides the basic information on the usage of this SDk in performing various operations offered by the Restcomm-Rest APIs. The Restcomm REST API allows you to query meta-data about your account, phone numbers, calls, text messages, and recordings. You can also do some communications control like initiate outbound calls and send text messages.

.*Table of Content*

* Installation +
* Feedback +
* Getting Started +
** Api Credentials +
** Examples +
*** Accounts +
**** Account Details +
**** Change Account Password +
**** Create Sub Account +
**** Close Sub Account +
**** Sub Account Details +
*** Sms +
*** Call +

== *Installation*

Install from PyPi using *pip*, a package manager for Python. Go to the terminal and type:

`$ pip install Restcomm_Python_SDk`

if it doesn’t work, try using:

`$ sudo pip install Restcomm_Python_SDk`

Don’t have pip installed? Try installing it, by running this from the command line:

`$ curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python`

Or, you can *download the source code (ZIP)* for Restcomm-Python, and then run in the terminal:

`$ python setup.py install`

Or, you can run it by using:

`$ sudo python setup.py install`

if you want to install it in *python 3* or above, try using:

`$ sudo python3 setup.py install`

== *Feedback*

Report any feedback or problems with this Release Candidate to the *_Github Issues_* for Restcomm-Python

== *Getting Started*

Getting started with the Restcomm API is damn easy. We basically have to create a client and pass it to the required class as and when called. So, now we are ready to go

== *API Credentials*

The `Restcomm` needs your `Restcomm credentials` to use its API. If you don’t have one, first try getting it and then read further. If you have Restcomm credentials, you can either pass these directly to the constructor or via environment variables.

`from Restcomm_Python_SDk import client` +

`AccountSid = “XXXXXXXXXXXXXXXXXX”` +
`AuthToken = “YYYYYYYYYYYYYYYY”` +
`BaseUrl = “https://ZZZZZZZZZZZZZZ”` +
`client = client(AccountSid, AuthToken, BaseUrl)` +

== *Examples*

== *Accounts*

=== *Get Account Details*

`from Restcomm_Python_SDk import AccountDetails` +

`getinfo = AccountDetails(client).Details()` +
To get Details of the main Account Sid +
`Sid = getinfo['Sid']` +
To get Details of the Date when the Account was created +
`Date_Created = getinfo['DateCreated']` +
and similarly for 'other' details, type +
`print(getinfo['other'])` 

=== *Change Account Password*

`from Restcomm_Python_SDk import ChangeAccountPassword` +

`data = ChangeAccountPassword('newPassword12345', client).ChangePassword()` +
To get new Authentication Token +
`newAuthToken = data['AuthToken']` +

NOTE: After Changing the Account Password, you need to update with new Account Sid and Authentication Token +
To do so, Simply call client function +
`client = client(AccountSid, newAuthToken, BaseUrl)` +

=== *Create Sub Account*

`from Restcomm_Python_SDk import CreateSubAccount` +

`data = CreateSubAccount('friendlyName', 'friendly@gmail.com', 'newPassword321', client).Create()` +
To get details of new Sub Account Created +
`Status = data['Status']` +
`SubSid = data['Sid']` +
`Date_Created = data['DateCreated']` +

=== *Close Sub Account*

`from Restcomm_Python_SDk import CloseSubAccount` +

`data = CloseSubAccount(SUBACCOUNTSID, client).Close()` +
`Status = data['Status']` +

=== *Sub Account Details*

`from Restcomm_Python_SDk import SubAccountDetails` +

To get the Details of all the Sub Accounts +
`getDetails = SubAccountDetails(client).Details()` +
To get the Details of SubAccount with give Sid +
`getInfo = getDetails['Sid']` +

== *Make a Call*

`from Restcomm_Python_SDk import client` +
`from Restcomm_Python_SDk import Makecall` +

`AuthToken = “YYYYYYYYYYYYYYYY”` +
`BaseUrl = “https://ZZZZZZZZZZZZZZ”` +
`client = client(AccountSid, AuthToken, BaseUrl)` +

`call = Makecall(from = “9840275164”, to = “8282900154”, url = “https://cloud.restcomm.com/restcomm/demos/hello-play.xml
”, client)` +
`print(call[“Sid”])` +

== *Send an SMS*

`from Restcomm_Python_SDk import client` +
`from Restcomm_Python_SDk import SendSms` +

`AccountSid = “XXXXXXXXXXXXXXXXXX”` +
`AuthToken = “YYYYYYYYYYYYYYYY”` +
`BaseUrl = “https://ZZZZZZZZZZZZZZ”` +
`client = client(AccountSid, AuthToken, BaseUrl)` +

`message = SendSms(to = “9840275164”, from = “8282900154”, body = “This is a test message. Please ignore it! ”, client)` +
