= *Restcomm-Python* +

Restcomm_Python_SDk is a module for using the *Restcomm Rest API*. This Documentation provides the basic information on the usage of this SDk in performing various operations offered by the Restcomm-Rest APIs. The Restcomm REST API allows you to query meta-data about your account, phone numbers, calls, text messages, and recordings. You can also do some communications control like initiate outbound calls and send text messages.

.*Table of Content*

* Installation +
* Feedback +
* Getting Started +
** Api Credentials +
** Examples +
*** Accounts +
**** Account Details +
**** Change Account Password +
**** Create Sub Account +
**** Close Sub Account +
**** Sub Account Details +
*** Call +
**** Make a Call +
**** Get Call Details +
**** Redirect a Call +
**** Make Conference Call +
**** Mute a Participant +
**** UnMute a Participant +
**** Terminate a Call +
**** Filter Call list +
*** Sms +
**** Send Sms +
**** Get Sms List +
**** Filter Sms List +
*** Applications +
**** Create an Application +
**** Delete an Application +
**** Update an Application +
**** Get Application List + 
*** Available Phone Number +
**** Number Availability +
*** Client +
**** Create a client +
**** Delete a client +
**** Change Client Password +
**** Get Client List +
*** Email +
**** Send an Email +
*** Gateway +
**** Create Gateway +
**** Get Gateway list +
**** Update Gateway +
**** Delete Gateway +
*** Incoming Number +
**** Get Incoming Number List +
**** Attach a phone Number +
**** Delete a phone Number +
*** Notifications +
**** Get Notification List +
**** Filter Notification List +
*** Recordings +
**** Get Recording List +
**** Filter Recording List +
*** Transcriptions +
**** Get Transcription List +
**** Filter Transcription List +
*** Usage +
**** Get Usage List +
*** UssdPush +
**** Push Ussd Message +
*** Supervisor/Monitoring Service +
**** Get Metric +

== *Installation*

Install from PyPi using *pip*, a package manager for Python. Go to the terminal and type:

`$ pip install Restcomm_Python_SDk`

if it doesn’t work, try using:

`$ sudo pip install Restcomm_Python_SDk`

Don’t have pip installed? Try installing it, by running this from the command line:

`$ curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python`

Or, you can *download the source code (ZIP)* for Restcomm-Python, and then run in the terminal:

`$ python setup.py install`

Or, you can run it by using:

`$ sudo python setup.py install`

if you want to install it in *python 3* or above, try using:

`$ sudo python3 setup.py install`

== *Feedback*

Report any feedback or problems with this Release Candidate to the *_Github Issues_* for Restcomm-Python

== *Getting Started*

Getting started with the Restcomm API is damn easy. We basically have to create a client and pass it to the required class as and when called. So, now we are ready to go

== *API Credentials*

The `Restcomm` needs your `Restcomm credentials` to use its API. If you don’t have one, first try getting it and then read further. If you have Restcomm credentials, you can either pass these directly to the constructor or via environment variables.

`from Restcomm_Python_SDk import client` +

`AccountSid = “XXXXXXXXXXXXXXXXXX”` +
`AuthToken = “YYYYYYYYYYYYYYYY”` +
`BaseUrl = “https://ZZZZZZZZZZZZZZ”` +
`client = client(AccountSid, AuthToken, BaseUrl)` +

== *Examples*

== *Accounts*

|===
|Property |Description

|Sid
|A string that uniquely identifies this account.

|DateCreated
|The date that this account was created.

|DateUpdated
|The date that this account was last updated.

|FriendlyName
|A description of this account, up to 64 characters long. By default the FriendlyName is your email address.

|Status
|The status of this account. Possible values are active, suspended, and closed.

|AuthToken
|The authorization token for this account. This should not be shared.

|Uri
|The URI for this account, relative to https://localhost:port/restcomm.

|===

=== Get Account Details

`from Restcomm_Python_SDk import AccountDetails` +

`getinfo = AccountDetails(client).Details()` +
To get Details of the main Account Sid +
`Sid = getinfo['Sid']` +
To get Details of the Date when the Account was created +
`Date_Created = getinfo['DateCreated']` +
and similarly for 'other' details, type +
`print(getinfo['other'])` 

=== Change Account Password

`from Restcomm_Python_SDk import ChangeAccountPassword` +

`data = ChangeAccountPassword('newPassword12345', client).ChangePassword()` +
To get new Authentication Token +
`newAuthToken = data['AuthToken']` +

NOTE: After Changing the Account Password, you need to update with new Account Sid and Authentication Token +
To do so, Simply call client function +
`client = client(AccountSid, newAuthToken, BaseUrl)` +

=== Create Sub Account

`from Restcomm_Python_SDk import CreateSubAccount` +

`data = CreateSubAccount('friendlyName', 'friendly@gmail.com', 'newPassword321', client).Create()` +
To get details of new Sub Account Created +
`Status = data['Status']` +
`SubSid = data['Sid']` +
`Date_Created = data['DateCreated']` +

=== Close Sub Account

`from Restcomm_Python_SDk import CloseSubAccount` +

`data = CloseSubAccount(SUBACCOUNTSID, client).Close()` +
`Status = data['Status']` +

=== Sub Account Details

`from Restcomm_Python_SDk import SubAccountDetails` +

To get the Details of all the Sub Accounts +
`getDetails = SubAccountDetails(client).Details()` +
To get the Details of SubAccount with give Sid +
`getInfo = getDetails['Sid']` +

== *Call*

|===
|Property |Description

|Sid
|A string that uniquely identifies this call.

|ParentCallSid
|A string that uniquely identifies the call that created this leg.

|DateCreated
|The date that this call was created.

|DateUpdated
|The date that this call was last updated.

|AccountSid
|The unique id of the Account that created this call.

|To
|The phone number or identifier that will be the recipient of this call.

|From
|The phone number or identifier that originated this call.

|PhoneNumberSid
|If the call was inbound, this is the Sid of the IncomingPhoneNumber that received the call.

|Status
|A string representing the status of the call. Possible values are queued, ringing, in-progress, completed, failed, busy and no-answer.

|StartTime
|The start time of the call. Empty if the call has not yet been started.

|EndTime
|The end time of the call. Empty if the call has not ended..

|Duration
|The length of the call in seconds.

|Price
|The charge for this call, in the currency associated with the account. Populated after the call is completed.

|Direction
|A string describing the direction of the call. Possible values are inbound, outbound-api, and outbound-dial

|AnsweredBy
|If this call was initiated with answering machine detection, either human or machine. Empty otherwise.

|ApiVersion
|Displays the current API version

|ForwardFrom
|If this call was an incoming call forwarded from another number, the forwarding phone number (depends on carrier supporting forwarding). Empty otherwise.

|CallerName
|If this call was an incoming call, the caller’s name. Empty otherwise.

|Uri
|The URI for this account, relative to https://localhost:port/restcomm.

|===

=== Make a Call

`from Restcomm_Python_SDk import Makecall` +

`call = Makecall(from = “9840275164”, to = “8282900154”, url = “https://cloud.restcomm.com/restcomm/demos/hello-play.xml
”, client).Call()` +
To get Call Sid +
`CallSid = call['sid']` +

=== Get Call Details

`from Restcomm_Python_SDk import GetCallDetail` +

`getDetails = GetCallDetail(client).GetDetails()` +
To get the required info, you can simply type +
`startTime = getDetails['start_time']` +
`price = getDetails['price']` +

=== Redirect a Call

`from Restcomm_Python_SDk import RedirectCall` +

To Redirect a Call to a person, you need to have its Calling Sid +
`redirectCall = RedirectCall(URL, CALLSID, client).Redirect()` +

=== Make Conference Call

`from Restcomm_Python_SDk import ConferenceCall` +

To make a Conference Call, you need to have Calling Sid of the person and the Url +
`ConCall = ConferenceCall(URL, CALLSID, client).Conference()` +

=== Mute a Participant

`from Restcomm_Python_SDk import MuteParticipant` +

To Mute a participant during a conference call, you need to have the Participant Sid and conference Sid +
`Mute = MuteParticipant(PARTICIPANTSID, CONFERENCESID, client).Mute()` +

=== UnMute a Participant

`from Restcomm_Python_SDk import UnMuteParticipant` +

To UnMute a participant during a conference call, you need to have the participant sid and conference sid +
`Unmute = UnMuteParticipant(PARTICIPANTSID, CONFERENCESID, client).UnMute()` +

=== Terminate a call

`from Restcomm_Python_SDk import TerminateCall` +

To Terminate an Ongoing call, you need to provide user authentication data with status detail as completed and Participant Sid and call the 'TerminateCall' class and pass these data to the 'Terminate' function. +
To Terminate a ringing call, you need to do the above said process with only one modification. Instead of status as completed, provid status as canceled and call the same class and function and pass the data's. +

Ongoing call +
`terminatecall = TerminateCall(PARTICIPANT SID, "completed", client).Terminate()` +
Ringing call +
`terminatecall = TerminateCall(PARTICIPANT SID, "canceled", client).Terminate()` +

=== Filter Call List

To filter the list of incoming and outgoing calls, you have two options. Either you can filter the list according to the page numbers or you can filter the list according the Sender data. To filter the list, you need to provide user authentication data to the client class along with filter option data for example Page no. 1 and call the 'CallFilter' class and call 'FilterFrom' or 'FilterPage' function and pass these data's to the respective class and call the functions. For example, To filter the list according to the page no. +

`from Restcomm_Python_SDk import CallFilter` +

`filterpage = CallFilter("1", client).FilterPage()` +
`filterfrom = CallFilter("9038455021", client).FilterPage()` +

== *Sms*

|===
|Property |Description

|Sid
|A string that uniquely identifies this SMS Message.

|DateCreated
|The date that this SMS Message was created.

|DateUpdated
|The date that this SMS Message was last updated.

|DateSent
|The date that the SMS was sent or received by RestComm.

|AccountSid
|The unique id of the Account that sent or received this SMS message.

|To
|The phone number or short code that received the message.

|From
|The phone number or short code that initiated the message.

|Status
|The status of this SMS message. Possible values are queued, sending, sent, failed, and received.

|Direction
|The direction of this SMS message. Possible values are incoming, outbound-api, outbound-call.

|ApiVersion
|The API version RestComm used to handle the SMS message.

|Uri
|The URI for this account, relative to https://localhost:port/restcomm.

|===

=== Send Sms

`from Restcomm_Python_SDk import SendSms` +

`message = SendSms(to = “9840275164”, from = “8282900154”, body = “This is a test message. Please ignore it! ”, client)` +

=== Get Sms List

`from Restcomm_Python_SDk import SmsList` +

To get list of all the Sms sent and received, We need to pass the client data to the required class +
`getlist = SmsList(client).GetList()` +
To get price information and other details, you can simply type +
`price = getlist['Price']` +
`priceUnit = getlist['PriceUnit']` +
`SmsSid = getlist['Sid']` +

=== Filter Sms List

To filter the list of Sms, you can either filter it by passing the page information to get list of sms according to page no. or else you can also filter it by providing the information of the person you want to view the Sms +
To view Sms according to the information of the person +

`from Restcomm_Python_SDk import FilterSmsList` +

`filterinfo = FilterSmsList('alice', client).GetFilterlist()` +
`SmsSid = filterinfo['Sid']` +

To view Sms according to the number of page +

`from Restcomm_Python_SDk import SmsPagingInformation` +

`filterinfo = SmsPagingInformation('1', client).PageInfo()` +
`smsSid = filterinfo['Sid']` +

== *Applications*

|===
|Property |Description

|Sid
|A string that uniquely identifies this Application.

|DateCreated
|The date when this Application was created.

|DateUpdated
|The date wher this Application was last updated.

|FriendlyName
|A friendly name for this Application.

|AccountSid
|The unique ID of the Account that owns this Application.

|ApiVersion
|Version of the API applied to this Application.

|HasVoiceCallerIdLookup
|Look up the caller’s caller-ID name from the CNAM database. Either true or false.

|Uri
|The URI for this Application, relative to https://localhost:port/restcomm.

|RcmlUrl
|The HTTP address that RestComm will use to get the RCML of this Application.

|Kind
|The kind of this Application. (Supported values: voice, sms or ussd)

|===

=== Create an Application

To Create an application, you need to provide the Application name and the kind of application to be created +
`from Restcomm_Python_SDk import CreateApplication` +

`createApp = CreateApplication('demoApp', 'voice', client).Create()` +
This will create an Application and all the details will be stored in createApp. You can extract the information according to your choice, for example +
`Date_Created = createApp['DateCreated']` +
`AppSid = createApp['Sid']` +
`Date_Updated = createApp['DateUpdated']` +

=== Delete an Application

To Delete an Application, you need to provide the Application Sid +
`from Restcomm_Python_SDk import DeleteApplication` +

`deleteApp = DeleteApplication(APPSID, client).Delete()` +
This will delete the Application with the given Sid and the details will be stored in deleteApp. You can check it by typing +
`Date_Updated = deleteApp['DateUpdated']` +

=== Update an Application

If you want to update the Application name, you need to provide the Application Sid +
`from Restcomm_Python_SDk import UpdateApplication` +

`updateApp = UpdateApplication(APPSID, 'newdemoApp', client).Update()` +
This will Update the Application with new Application name and the details will be stored in updateApp. You can check it by typing +
`Date_Created = updateApp['DateCreated']` +
`Date_Updated = updateApp['DateUpdated']` +
`AppSid = updateApp['Sid']` +

=== Get Application list

To get the list of all Applications Created, you can simply call the GetApplicationList class and provide the authentication data to access the list +
`from Restcomm_Python_SDk import GetApplicationList` +

`getinfo = GetApplicationList(client).GetList()` +
getinfo will contain all the data of the applications. you can simply get your desired result by typing +
`AppSid = getinfo['Sid']` +
`friendlyName = getinfo['FriendlyName']` +
`kind = getinfo['Kind']` +

== *Available Phone Number* 

|===
|Property |Description

|FriendlyName
|A nice-formatted version of the phone number

|PhoneNumber
|The phone number, in E.164 (i.e. "+1") format

|Lata
|The LATA of this phone number

|RateCenter
|The rate center of this phone number

|Latitude
|The latitude coordinate of this phone number

|Longitude
|The Longitude coordinate of this phone number

|Region
|The two-letter state or province abbreviation of this phone number.

|PostalCode
|The postal(zip) code of this phone number

|IsoCountry
|The ISO country code of this phone number

|Capabilities
|This is a set of boolean properties that indicate whether a phone number can receive calls or messages. Possible capabilities are Voice, SMS, and MMS with each having a value of either true or false.

|===

The following properties are available for phone numbers outside the US and Canada:

|===
|Property |Description

|FriendlyName
|A nicely-formatted version of the phone number.

|PhoneNumber
|The phone number, in[E.164] (i.e. "+44") format

|IsoCountry
|The ISO country code of this phone number

|Capabilites
|This is a set of boolean properties that indicate whether a phone number can receive calls or messages. Possible capabilities are Voice, Sms, and MMS with each having a value of either true or false

|===

=== Number Availability

To get the list of all the numbers available, you need to provide the area code for which you need to check the availability of the number +
`from Restcomm_Python_SDk import NumberAvailability` +

`getlist = NumberAvailability('305', client).Availability()` +
This will give the list of all the numbers available. To check +
`numbers = getlist['phNumber']` +
`friendlyName = getlist['friendlyName']` +
`smsCapable = getlist['smsCapable']` +

== *Client*

|===
|Property |Description

|Sid
|A string that uniquely identifies this client

|DateCreated
|The date that this client was created

|DateUpdated
|The date that this client was last updated

|FriendlyName
|A friendly name for this client

|AccountSid
|The unique id of the Account that owns this phone number

|ApiVersion
|Calls to this phone number will create a new RCML session with this API version

|Login
|The name that is used inside the <Client> noun. This is also used by the user agent as the user name used for registration and outbound dialing

|Password
|The password used by the user agent during registration and outbound dialing

|Status
|The client status the possible values are 0 for disabled and 1 for enabled

|VoiceUrl
|The URL Restcomm will request when this client makes an outbound call.

|VoiceMethod
|The HTTP method RestComm will use when requesting the above Url.Either GET or POST

|VoiceFallbackUrl
|The URL that Restcomm will request if execution of VoiceUrl fails for any reason

|VoiceFallbackMethod
|The HTTP method RestComm will use when requesting the VoiceFallbackUrl. Either GET or POST

|VoiceApplicationSid
|If this entry contains an Sid to a voice application then Restcomm will ignore these voice URLs and use the voice URLs specified by the voice application

|Uri
|The URI for this Client, relative to https://localhost:port/restcomm

|===

=== Create a Client

To Create a client, you need to provide the client Login Id and password and pass it to CreateClient class with user Authentication +
`from Restcomm_Python_SDk import CreateClient` +

`create = CreateClient('demoId', 'demoPassword', client).Create()` +
This will create the client with Login Id and Password as mentioned above and the details are stored in `create`. +
`status = create['status']` +
`clientSid = create['sid']` +
`Date_Created = create['DateCreated']` +
`Date_Updated = create['DateUpdated']` +

=== Delete a client

To Delete a client, you need to provide the client Sid and pass it to DeleteClient class with user Authentication +
`from Restcomm_Python_SDk import DeleteClient` +

`deleteclient = DeleteClient(CLIENTSID, client).Delete()` +
This will delete the client with the Client Sid as mentioned above and the details are stored in `deleteclient`. +
`status = deleteclient['status']` +

=== Change Client Password

To change the Password of a client, you need to provide the client Sid and new Password and pass it to ChangeClientPassword class along with user Authentication +
`from Restcomm_Python_SDk import ChangeClientPassword` +

`change = ChangeClientPassword(CLIENTSID, 'newPassword', client).ChangePassword()` +
This will replace the Password with the new Password provided above and the details are stored in `change`. +
`token = change['AuthToken']` +
`Date_Updated = change['DateUpdated']` +

=== Get Client List

To get list of all the clients, you need to pass the user Authentications to the ClientList class +
`from Restcomm_python_SDk import ClientList` +

`getinfo = ClientList(client).GetList()` +
This will store all the information of the clients in `getinfo` and you can access it by simply +
`clientsid = getinfo['sid']` +

== *Email*

|===
|Property |Description

|DateSent
|The date that this Email Message was send

|AccountSid
|The unique id of the Account that sent this Email message

|From
|The Email address that initiated the message

|To
|The Email address of the recipient

|Body
|The text body of the email message

|Subject
|The subject of the email message

|===

=== Send an Email

To send an Email, you need to provide the sender and receivers email address and pass it to SendEmail class along with user Authentication +
You also need to provide Subject of the Email along with the message +
`from Restcomm_Python_SDk import SendEmail` +

`sendmail = SendEmail('demo1@gmail.com', 'demo2@gmail.com', 'testMail', 'This is the test mail. Please ignore it!', client).Send()` +
This will send the Email to the respective person and the details are stored in `sendmail` +
`Date_Sent = sendmail['DateSent']` +

== *Gateway*

|===
|Property |Description

|FriendlyName
|A friendly version of the gateway

|UserName
|The username that will be used to register to this gateway

|Password
|The password that will be used to register to this gateway

|Proxy
|The proxy address of the gateway

|Register
|Boolean flag to register or not the gateway

|TTL
|Time to live for the Register

|===

=== Create Gateway

To create a Gateway, you need to provide the gateway friendly name, user name, gateway password and the proxy in which the gateway are working and pass it to CreateGateway class along with the user Authentications +
`from Restcomm_Python_SDk import CreateGateway` +

`create = CreateGateway('myGateway', 'username', 'userpassword', 'my.gateway.com', client).Create()` +
This will create the required Gateway with the friendly name, username, password and proxy as provided above and the details are stored in `create`. To access it, type` +
`Date_Created = create['DateCreated']` +

=== Get Gateway List

To get the list of all the Gateway created, you need to provide user Authentication and pass it to GetListGateway class +
`from Restcomm_Python_SDk import GetListGateway` +

`getinfo = GetListGateway(client).GetList()` +
This will store all the details of the Gateway created, in `getinfo`. To get the required details, type +
`GatewaySid = getinfo['sid']` +
`Date_Created = getinfo['DateCreated']` +

=== Update Gateway

To update the Gateway, you need to provide the Gateway Sid and the required changes which you want to make like change friendly name and username and pass it to UpdateGateway class along with user Authentication
`from Restcomm_Python_SDk import UpdateGateway` +

`updategateway = UpdateGateway(GATEWAYSID, 'newGateway', 'newUsername', client).Update()` +
This will update the Gateway with the new friendly name and username as provided above and the details are stored in `updategateway`. To access it, type +
`Date_Updated = updategateway['DateUpdated']` +

=== Delete Gateway

To Delete the Gateway, you need to provide the Gateway Sid and pass it to the DeleteGateway class along with user Authentication +
`from Restcomm_Python_SDk import DeleteGateway` +

`DeleteGateway(GATEWAYSID, client).Delete()` +

== *Incoming Number*

|===
|Property |Description

|Sid
|A 34 character string that uniquely identifies this resource

|DateCreated
|The date that this resource was created, given as GMT http://www.ietf.org/rfc/rfc2822.txt[RFC 2822] format.

|DateUpdated
|The date that this resource was last updated, given as GMT http://www.ietf.org/rfc/rfc2822.txt[RFC 2822] format

|FriendlyName
|A human readable descriptive text for this resource, up to 64 characters long. By default, the FriendlyName is a nicely formatted version of the phone number

|AccountSid
|The unique id of the Account responsible for this phone number.

|PhoneNumber
|The incoming phone number. e.g., +16175551212 (E.164 format)

|ApiVersion
|Calls to this phone number will start a new RCML session with this API version

|VoiceCallerIdLookup
|Look up the caller's caller-ID name from the CNAM database($0.01 per look up). Either true or false

|VoiceUrl
|The URL Restcomm will request when this phone number receives a call

|VoiceMethod
|The HTTP method Restcomm will use when requesting the above Url. Either GET or POST

|VoiceFallbackUrl
|The URL that Restcomm will request if an error occurs retrieving or executing the RCML requested by Url

|VoiceFallbackMethod
|The HTTP method Restcomm will use when requesting the VoiceFallbackUrl. Either GET or POST

|StatusCallback
|The URL that Restcomm will request to pass status parameters(such as call ended) to your application

|StatusCallbackMethod
|The HTTP method Restcomm will use to make requests to the StatusCallback URL. Either GET or POST

|VoiceApplicationSid
|The 34 character sid of the application Restcomm should use to handle phone calls to this number. If a VoiceApplicationSid is present, Restcomm will ignore all of the voice urls above and use those set on the application

|VoiceApplicationName
|The application name

|SmsUrl
|The URL Restcomm will request when receiving an incoming SMS message to this number

|SmsMethod
|The HTTP method Restcomm will use when making requests to the SmsUrl. Either GET or POST

|SmsFallbackUrl
|The URL that Restcomm will request if an error occurs retrieving or executing the RCML from SmsUrl

|SmsFallbackMethod
|The HTTP method Restcomm will use when requesting the above URL. Either GET or POST

|SmsApplicationSid
|The 34 character sid of the application Restcomm should use to handle SMSs sent to this number. If a SmsApplicationSid is present, Restcomm will ignore all of the SMS urlsabove and use those set on the application

|SmsApplicationName
|The Application name

|UssdUrl
|The URL Restcomm will request when receiving an incoming USSD request to this number

|UssdMethod
|The HTTP method Restcomm will use when making requests to the UssdUrl. Either GET or POST

|UssdFallbackUrl
|The URL that Restcomm will request if an error occurs retrieving or executing the RCML from UssdUrl

|UssdFallbackMethod
|The HTTP method Restcomm will use when requesting the above URL. Either GET or POST

|UssdApplicationSid
|The 34 character sid of the application Restcomm should use to handle USSD requests to this number. If a UssdApplicationSid is present, Restcomm will ignore all of the Ussd urls above and use those set on the application

|UssdApplicationName
|The application name

|ReferUrl
|The URL Restcomm will request when receiving a SIP Refer request to this number

|ReferMethod
|The HTTP method Restcomm will use when making requests to the ReferUrl. Either GET or POST

|ReferApplicationSid
|The 34 character sid of the application Restcomm should use to handle SIP Refer requests to this number. If a ReferApplicationSid is present, Restcomm will ignore all of the Refer urls above and use those set on the application.

|ReferApplicationName
|The application name

|Capabilities
|This is a set of boolean properties that indicate whether a phone number can receive calls or messages. Possible capabilities are Voice, SMS, and MMS with each having a value of either true or false

|Uri
|The URI for this resource, relative to https://api.Restcomm.com

|===

=== Get Incoming Number List

To get the list of all Incoming Numbers, you need to pass user Authentication to PhoneNumberList class +
`from Restcomm_Python_SDk import PhoneNumberList` +

`getlist = PhoneNumberList(client).GetList()` +
This will store all the Incoming Phone Numbers in `getlist`. you can access it to get your required data +
`callSid = getlist['sid']` +
`phoneNumber = getlist['phone_number']` +
`friendlyname = getlist['friendly_name']` +
`capable = getlist['capabilities']` +

=== Attach a Phone Number

To attach a Phone Number to an application, you need to provide the Phone Number and voice Url and pass it to the AttachPhoneNumber class along with user Authentication
`from Restcomm_Python_SDk import AttachPhoneNumber` +

`AttachPhoneNumber(PHONENUMBER, VOICEURL, client).Attach()` +

=== Delete a Phone Number

To delete a phone Number, you need to provide the calling sid and pass it to the DeletePhoneNumber class along with user Authentication
`from Restcomm_Python_SDk import DeletePhoneNumber` +

`DeletePhoneNumber(CALLSID, client).Delete()` +

== *Notifications*

|===
|Property |Description

|Sid
|A string that uniquely identifies this transcription.

|DateCreated
|The date that this transcription was created

|DateUpdated
|The date that this transcription was last updated

|AccountSid
|The unique id of the Account that created this transcription

|CallSid
|CallSid is the unique id of the call during which the notification was generated. Empty if the notification was generated by the Restful APIs without regard to a specific phone call

|ApiVersion
|The RestComm API version in use when this notification was generated. May be empty for events that don't have a specific API version

|Log
|An integer log level corresponding to the type of notification:0 is ERROR, 1 is WARNING.

|ErrorCode
|A unique error code for the error condition. You can lookup errors, in our Error Dictionary.

|MoreInfo
|A URL for more information about the error condition. The URL is a page in our Error Dictionary

|MessageText
|The text for the notification

|MessageDate
|The date the notification was actually generated.

|RequestUrl
|The URL of the resource that caused the notification to be generated

|RequestMethod
|The HTTP method in use for the request that caused the notification to be generated.

|RequestVariables
|The HTTP GET or POST variables that RestComm generated and sent to your server. Also, if the notification was generated by the Restful APIs, this field will include any HTTP POST or PUT variables you sent.

|ResponseHeaders
|The HTTP headers returned by your server

|ResponseBody
|The HTTP body returned by your server

|Uri
|The URI for this account, relative to https://localhost/restcomm.

|===

=== Get Notification List

To get list of Notifications, call the NotificationList class and pass user Authentication +
`from Restcomm_Python_SDk import NotificationList` +

`getlist = NotificationList(client).GetList()` +
This will store all the details of the notifications in `getlist`. you can access it similarly by +
`notificationsid = getlist['sid']` +
`Date_Created = getlist['DateCreated']` +
`Date_Updated = getlist['DateUpdated']` +

=== Filter Notification List

You can filter the list of notifications by two way. One way is to filter it by using error code or the second way is to provide page information. To Filter it by using Error Code, you need to provide the error code and pass it to NotificationFilter class along with user Authentications or else if you want to filter it using page information, then provide page information and pass it to NotificationFilter class along with user Authentications. +
`from Restcomm_Python_SDk import NotificationFilter` +

`getlist = NotificationFilter(ERRORCODE, client).FilterErrorCode()` +
or else
`getlist = NotificationFilter('1', client).FilterPage()` +
These will store the details as per filter option in `getlist`. You can access it by typing +
`notificationsid = getlist['sid']` +

== *Recordings*

|===
|Property |Description

|Sid
|A string that uniquely identifies this recording

|DateCreated
|The date that this recording was created

|DateUpdated
|The date that this recording was last updated

|AccountSid
|The unique id of the Account that created this recording

|CallSid
|The unique id of the call during which the recording was made

|Duration
|The length of the recording, in seconds

|ApiVersion
|The API version in use during the recording

|Uri
|The URI for this account, relative to https://localhost:restcomm.

|FileUri
|The File URI for this recording, relative to https://localhost:restcomm. It can be used to access the WAV file

|S3Uri
|The S3 URI for this recording-Exists ONLY IF Amazon S3 integration is enabled and security level is NONE-

|===

=== Get Recording List

To get list of Recordings, call the RecordingList class and pass user Authentication +
`from Restcomm_Python_SDk import RecordingList` +

`getlist = RecordingList(client).GetList()` +
This will store all the details of the Recording in `getlist`. you can access it similarly by +
`Recordingsid = getlist['sid']` +
`Date_Created = getlist['DateCreated']` +
`Date_Updated = getlist['DateUpdated']` +

=== Filter Recording List

You can filter the list of Recordings by two way. One way is to filter it by using calling Sid or the second way is to provide page information. To Filter it by using calling Sid, you need to provide the Call Sid and pass it to RecordingFilter class along with user Authentications or else if you want to filter it using page information, then provide page information and pass it to RecordingFilter class along with user Authentications. +
`from Restcomm_Python_SDk import RecordingFilter` +

`getlist = RecordingFilter(CALLSID, client).FilterCallSid()` +
or else
`getlist = RecordingFilter('1', client).FilterPage()` +
These will store the details as per filter option in `getlist`. You can access it by typing +
`recordingsid = getlist['sid']` +

== *Transcriptions*

|===
|Property |Description

|Sid
|A string that uniquely identifies this transcription

|DateCreated
|The date that this transcription was created

|DateUpdated
|The date that this transcription was last updated

|AccountSid
|The unique id of the Account that created this transcription

|Status
|A string representing the status of the transcription. Possible values are in-progress, completed, and failed.

|RecordingSid
|The unique id of the Recording this Transcription was made of.

|Duration
|The duration of the transcribed audio, in seconds

|TranscriptionText
|The text content of the transcription

|Uri
|The URI for this account, relative to https://localhost/restcomm.

|===

=== Get Transcription List

To get list of Transcriptions, call the TranscriptionList class and pass user Authentication +
`from Restcomm_Python_SDk import TranscriptionList` +

`getlist = TranscriptionList(client).GetList()` +
This will store all the details of the Transcriptions in `getlist`. you can access it similarly by +
`transcriptionsid = getlist['sid']` +
`Date_Created = getlist['DateCreated']` +
`Date_Updated = getlist['DateUpdated']` +

=== Filter Transcription List

You can filter the list of transcriptions by two way. One way is to filter it by using Transcription Text or the second way is to provide page information. To Filter it by using Transcription Text, you need to provide the Transcription Text and pass it to TranscriptionFilter class along with user Authentications or else if you want to filter it using page information, then provide page information and pass it to TranscriptionFilter class along with user Authentications. +
`from Restcomm_Python_SDk import TranscriptionFilter` +

`getlist = TranscriptionFilter(TRANSCRIPTIONTEXT, client).FilterText()` +
or else
`getlist = TranscriptionFilter('1', client).FilterPage()` +
These will store the details as per filter option in `getlist`. You can access it by typing +
`Transcriptionsid = getlist['sid']` +

== *Usage*

|===
|Property |Description

|Category
|The category of usage. See Usage Categories below

|Description
|A humble-readable description of the usage category

|AccountSid
|The Account that accrued the usage

|StartDate
|The first date for which usage is included in this UsageRecord, formatted as YYYY-MM-DD. All dates are in GMT.

|EndDate
|The last date for which usage is included in this UsageRecord, formatted as YYYY-MM-DD. All dates are in GMT.

|Usage
|The Amount of usage(e.g. the number of call minutes). This is frequently the same as Count, but may be different for certain usage categories like calls, where Count represents the number of calls and Usage represents the number of minutes

|UsageUnit
|The units in which Usage is measured. For example minutes for calls, messages for SMS.

|Count
|The number of usage events(e.g. the number of calls).

|CountUnit
|The units in which Count is measured. For example calls for calls, messages for SMS\

|Price
|The total price of the usage, in the currency associated with the account.

|PriceUnit
|The currency in which Price is measured, in ISO 4127 format(e.g. usd, eur, jpy).

|Uri
|The URI that returns only this UsageRecord, relative to https://Restcomm_IP_ADDRESS

|SubresourceUris
|Subresource Uris for this UsageRecord. See List Subresources.

|===

A Usage Record's Category defines the type of usage it represents. The full list of all categories is here, but you'll usually focus on just a few common categories

|===
|Category |Description

|calls
|All voice calls. Count is the number of calls and Usage is the number of minutes.

|sms
|All SMS messages. Count and Usage are both the number of message sent

|phonenumbers
|All phone numbers owned by the account

|recordings
|Recordings of voice calls. Count is the number of recordings and Usage is the number of recorded minutes. Note that Restcomm doesn't charge for making recordings(only storing them long term) so price will always be 0.

|transcriptions
|Transcriptions of voice calls. Count is the number of transcriptions and Usage is the number of transcribed minutes

|totalprice
|Total price of all usage. Usage will be the same as Price, and Count will be empty. Note that because some Restcomm costs may not be included in any usage category, the sum of the Price of all UsageRecords may not be equal to the Price of TotalPrice

|===

=== Get Usage List

To get list of Usage, you need to pass user authentications to the Usages class +
`from Restcomm_Python_SDk import Usages` +

`getinfo = Usages(client).GetList()` +
This will store the details of all usages in `getinfo`. To access it, simply type +
`sid = getinfo['sid']`

== *UssdPush*

=== Push Ussd Message

The USSD gateway to which Restcomm must send the UssdMessage must be configured in the restcomm.xml file. IP address and port must be configured. Username/password for the USSD are optional. +
To send a Ussd message to the configured USSD Gateway, call UssdPush class and pass all the required data with user Authentication +
`from Restcomm_Python_SDk import UssdPush` +

`sendsms = UssdPush("Restcomm", "123", YOUR_USSD_APP, client).Push()` +
This will store the details of all the send USSD messages in `sendsms`.

== *Supervisor/Monitoring Service*

|===
|Property |Description

|LiveCallDetails
|(optional) Set to true to get an array of live calls. Default value *false*

|===

The Supervisor API will provide the following metrics: +

* Real Time metrics
** Live incoming calls
** Live outgoing calls
** Live calls (total)
** Live call details array. An array with call details for each of the live calls
** Registered users
* Accumulated metrics
** Total calls since uptime
** Incoming calls since uptime
** Outgoing calls since uptime
** No Answered calls
** Busy calls
** Failed calls
** Not found calls
** Canceled calls
** Inbound Text messages to RMCL applications
** Inbound Text messages to Restcomm clients
** Inbound Text messages to outbound proxy
** Inbound Text messages with Not Found error
** Outgoing Text messages

=== Get Metric

To get the monitoring service metrics, call the Monitoring class and pass the user Authentication +
`from Restcomm_Python_SDk import Monitoring` +

`getMetric = Monitoring(client).GetMetric()` +
This will store all the details of the metrics in `getMetric`. To access it, simply type +
`InstanceId = getMetric['InstanceId']` +
`Revision = getMetric['Revision']` +


