'''
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 This code was generated by :
 Name: Md Sharique
 Email : nukles1.07@gmail.com
 '''

import requests
import json

class client(object):

    def __init__(self, Sid, AuthToken, BaseUrl):

        self.Sid=Sid
        self.AuthToken=AuthToken
        self.BaseUrl = BaseUrl

class CreateGateway(object):

    def __init__(self,FriendlyName,UserName,Password,Proxy,client):

        self.FriendlyName=FriendlyName
        self.UserName=UserName
        self.Password=Password
        self.Proxy=Proxy
        self.Sid=client.Sid
        self.AuthToken=client.AuthToken
        self.BaseUrl = client.BaseUrl

    def Create(self):

        try:

            Url = self.BaseUrl+'/Accounts/'+self.Sid+'/Management/Gateways.json'
            data = {'FriendlyName':self.FriendlyName,'UserName':self.UserName,'Password':self.Password,'Proxy':self.Proxy,'Register':'true','TTL':'3600'}
            r1 = requests.post(Url,data=data,auth=(self.Sid,self.AuthToken))

            if r1.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r1.status_code == 404:
                return "Base Url is Incorrect! Please verify and try again"
            elif r1.status_code == 400:
                return "Password is too weak"
            elif r1.status_code == 403:
                return "Invalid Proxy! Please enter correct proxy"
            else:
                content = json.loads(r1.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class GetlistGateway(object):

    def __init__(self,client):

        self.Sid=client.Sid
        self.AuthToken=client.AuthToken
        self.BaseUrl = client.BaseUrl

    def GetList(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Management/Gateways.json'
            r2 = requests.get(Url,auth=(self.Sid,self.AuthToken))

            if r2.status_code == 401:
                return ("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r2.status_code == 404:
                return "Base Url is Incorrect! Please verify and try again"
            else:
                content = json.loads(r2.text)
                return content

        except requests.HTTPError:
            return ("HTTP ERROR")
        except requests.ConnectionError:
            return ("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            return ("TIMEOUT ERROR")
        except requests.RequestException:
            return ("Invalid Url! Please check and try again")

class UpdateGateway(object):

    def __init__(self,GatewaySid,FriendlyName,UserName,client):

        self.Sid=client.Sid
        self.AuthToken = client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.GatewaySid=GatewaySid
        self.FriendlyName=FriendlyName
        self.UserName=UserName

    def Update(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Management/Gateways.json/'+self.GatewaySid
            data = {'FriendlyName':self.FriendlyName,'UserName':self.UserName}
            r3 = requests.post(Url,data=data,auth=(self.Sid,self.AuthToken))

            if r3.status_code == 401:
                print("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r3.status_code == 404:
                return "Base Url or Gateway Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r3.text)
                return content

        except requests.HTTPError:
            print("HTTP ERROR")
        except requests.ConnectionError:
            print("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            print("TIMEOUT ERROR")
        except requests.RequestException:
            print("Invalid Url! Please check and try again")

class DeleteGateway(object):

    def __init__(self,GatewaySid,client):

        self.Sid=client.Sid
        self.AuthToken=client.AuthToken
        self.BaseUrl = client.BaseUrl
        self.GatewaySid=GatewaySid

    def Delete(self):

        try:

            Url = self.BaseUrl+'/Accounts/' + self.Sid + '/Management/Gateways.json/'+self.GatewaySid
            r4 = requests.delete(Url, auth=(self.Sid,self.AuthToken))

            if r4.status_code == 401:
                print("Authentication Error! Please Enter Valid Account Sid and Authentication Token")
            elif r4.status_code == 404:
                return "Base Url or Gateway Sid is Incorrect! Please verify and try again"
            else:
                content = json.loads(r4.text)
                return content

        except requests.HTTPError:
            print("HTTP ERROR")
        except requests.ConnectionError:
            print("CONNECTION ERROR! Please check and try again")
        except requests.Timeout:
            print("TIMEOUT ERROR")
        except requests.RequestException:
            print("Invalid Url! Please check and try again")